In [33]:
import torch
print(torch.__version__)

2.11.0+cu128


In [34]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using cpu")

GPU is available
Using GPU: NVIDIA GeForce RTX 3050 6GB Laptop GPU


In [35]:
import torch

print("PyTorch:", torch.__version__)
print("CUDA compiled:", torch.version.cuda)
print("CUDA available:", torch.cuda.is_available())

PyTorch: 2.11.0+cu128
CUDA compiled: 12.8
CUDA available: True


## Creating a Tensor

In [36]:
# using empty
a = torch.empty(2,3)

In [37]:
# check type
type(a)

torch.Tensor

In [38]:
#using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [39]:
# using ones
torch.ones(2,3,4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [40]:
# use rand
torch.rand(2,3)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [41]:
# manual seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [42]:
# using tensor
torch.tensor([[1,2,3], [4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [43]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->",torch.linspace(0,10, 10))

# using eye
print("using eye ->",torch.eye(5))

# using full
print("using full ->",torch.full((3,3), 5))


using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes

In [44]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [45]:
x.shape

torch.Size([2, 3])

In [46]:
torch.empty_like(x)

tensor([[4615689221071321316, 4651718018103334230, 4671734013112731420],
        [4687746815133016974,          1092616192,                   0]])

In [47]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [48]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [55]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

## Tensor Data Types

In [52]:
# find data type
x.dtype

torch.int64

In [53]:
# assign data type
torch.tensor([1.0, 2.0, 3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [56]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

## Mathematical operations

1. Scalar Operation

In [64]:
x = torch.rand(2,2)
x

tensor([[0.2426, 0.7003],
        [0.5277, 0.2472]])

In [68]:
print(x)

# addition
print(x + 2)

# substraction
print(x - 2)

# multiplication
print(x * 2)

# division
print(x / 2)

# int division
print((x*100) // 2)

# mod
print(x % 2)

# power
print((x*100) ** 2)





tensor([[0.2426, 0.7003],
        [0.5277, 0.2472]])
tensor([[2.2426, 2.7003],
        [2.5277, 2.2472]])
tensor([[-1.7574, -1.2997],
        [-1.4723, -1.7528]])
tensor([[0.4851, 1.4007],
        [1.0554, 0.4944]])
tensor([[0.1213, 0.3502],
        [0.2638, 0.1236]])
tensor([[12., 35.],
        [26., 12.]])
tensor([[0.2426, 0.7003],
        [0.5277, 0.2472]])
tensor([[ 588.3479, 4904.7671],
        [2784.5535,  610.9972]])


2. elementwise operation

In [69]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.7909, 0.4235, 0.0169],
        [0.2209, 0.9535, 0.7064]])
tensor([[0.1629, 0.8902, 0.5163],
        [0.0359, 0.6476, 0.3430]])


In [70]:
# addition
print(a + b)

# substraction
print(a - b)

# multiplication
print(a * b)

# division
print(a / b)

# int division
print((a*100) // b)

# mod
print(a % b)

# power
print((a*100) ** b)



tensor([[0.9538, 1.3137, 0.5332],
        [0.2568, 1.6012, 1.0494]])
tensor([[ 0.6280, -0.4667, -0.4994],
        [ 0.1850,  0.3059,  0.3634]])
tensor([[0.1288, 0.3770, 0.0087],
        [0.0079, 0.6175, 0.2423]])
tensor([[4.8557, 0.4757, 0.0327],
        [6.1557, 1.4723, 2.0593]])
tensor([[485.,  47.,   3.],
        [615., 147., 205.]])
tensor([[0.1394, 0.4235, 0.0169],
        [0.0056, 0.3059, 0.0204]])
tensor([[ 2.0378, 28.0679,  1.3111],
        [ 1.1175, 19.1374,  4.3080]])


In [71]:
c = torch.tensor([1,-2,3,-4])
c

tensor([ 1, -2,  3, -4])

In [73]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [74]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [76]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [77]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [78]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [79]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [80]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

3. Reduction operation

In [86]:
e = torch.randint(size=(2,3),low=0, high=10, dtype=torch.float32)
e

tensor([[7., 9., 2.],
        [6., 7., 7.]])

In [87]:
# sum 
print(torch.sum(e))

# sum along columns
print(torch.sum(e, dim=0))

# sum along columns row
print(torch.sum(e, dim=1))


tensor(38.)
tensor([13., 16.,  9.])
tensor([18., 20.])


In [89]:
# mean
print(torch.mean(e))

# mean
print(torch.mean(e, dim=0))

# mean along row
print(torch.mean(e, dim=1))

tensor(6.3333)
tensor([6.5000, 8.0000, 4.5000])
tensor([6.0000, 6.6667])


In [91]:
# median
print(torch.median(e))

tensor(7.)


In [92]:
print(torch.max(e))
print(torch.min(e))

tensor(9.)
tensor(2.)


In [93]:
# product
torch.prod(e)

tensor(37044.)

In [94]:
# standard deviation
torch.std(e)

tensor(2.3381)

In [95]:
# variance
torch.var(e)

tensor(5.4667)

In [97]:
# argmax
torch.argmax(e)

tensor(1)

In [98]:
# argmin
torch.argmin(e)

tensor(2)