In [140]:
import torch
print(torch.__version__)

2.11.0+cu128


In [141]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using cpu")

GPU is available
Using GPU: NVIDIA GeForce RTX 3050 6GB Laptop GPU


In [142]:
import torch

print("PyTorch:", torch.__version__)
print("CUDA compiled:", torch.version.cuda)
print("CUDA available:", torch.cuda.is_available())

PyTorch: 2.11.0+cu128
CUDA compiled: 12.8
CUDA available: True


## Creating a Tensor

In [143]:
# using empty
a = torch.empty(2,3)

In [144]:
# check type
type(a)

torch.Tensor

In [145]:
#using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [146]:
# using ones
torch.ones(2,3,4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [147]:
# use rand
torch.rand(2,3)

tensor([[0.4001, 0.6241, 0.1347],
        [0.1615, 0.8335, 0.0517]])

In [148]:
# manual seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [149]:
# using tensor
torch.tensor([[1,2,3], [4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [150]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->",torch.linspace(0,10, 10))

# using eye
print("using eye ->",torch.eye(5))

# using full
print("using full ->",torch.full((3,3), 5))


using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes

In [151]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [152]:
x.shape

torch.Size([2, 3])

In [153]:
torch.empty_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [154]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [155]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [156]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

## Tensor Data Types

In [157]:
# find data type
x.dtype

torch.int64

In [158]:
# assign data type
torch.tensor([1.0, 2.0, 3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [159]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

## Mathematical operations

1. Scalar Operation

In [160]:
x = torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [161]:
print(x)

# addition
print(x + 2)

# substraction
print(x - 2)

# multiplication
print(x * 2)

# division
print(x / 2)

# int division
print((x*100) // 2)

# mod
print(x % 2)

# power
print((x*100) ** 2)





tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])
tensor([[2.7118, 2.7876],
        [2.4183, 2.9014]])
tensor([[-1.2882, -1.2124],
        [-1.5817, -1.0986]])
tensor([[1.4235, 1.5752],
        [0.8366, 1.8028]])
tensor([[0.3559, 0.3938],
        [0.2092, 0.4507]])
tensor([[35., 39.],
        [20., 45.]])
tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])
tensor([[5066.1006, 6202.8325],
        [1749.7931, 8125.4902]])


2. elementwise operation

In [162]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])
tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


In [163]:
# addition
print(a + b)

# substraction
print(a - b)

# multiplication
print(a * b)

# division
print(a / b)

# int division
print((a*100) // b)

# mod
print(a % b)

# power
print((a*100) ** b)



tensor([[1.5526, 1.7335, 0.6679],
        [1.2502, 0.9229, 1.3130]])
tensor([[ 0.4411, -0.2205, -0.2201],
        [-0.6455, -0.5661,  0.3346]])
tensor([[0.5540, 0.7391, 0.0994],
        [0.2866, 0.1328, 0.4030]])
tensor([[1.7938, 0.7743, 0.5042],
        [0.3190, 0.2397, 1.6841]])
tensor([[179.,  77.,  50.],
        [ 31.,  23., 168.]])
tensor([[0.4411, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.3346]])
tensor([[12.9043, 68.4935,  3.9760],
        [25.3098,  8.5444,  8.6544]])


In [164]:
c = torch.tensor([1,-2,3,-4])
c

tensor([ 1, -2,  3, -4])

In [165]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [166]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [167]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [168]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [169]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [170]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [171]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

3. Reduction operation

In [172]:
e = torch.randint(size=(2,3),low=0, high=10, dtype=torch.float32)
e

tensor([[8., 0., 7.],
        [0., 0., 9.]])

In [173]:
# sum 
print(torch.sum(e))

# sum along columns
print(torch.sum(e, dim=0))

# sum along columns row
print(torch.sum(e, dim=1))


tensor(24.)
tensor([ 8.,  0., 16.])
tensor([15.,  9.])


In [174]:
# mean
print(torch.mean(e))

# mean
print(torch.mean(e, dim=0))

# mean along row
print(torch.mean(e, dim=1))

tensor(4.)
tensor([4., 0., 8.])
tensor([5., 3.])


In [175]:
# median
print(torch.median(e))

tensor(0.)


In [176]:
print(torch.max(e))
print(torch.min(e))

tensor(9.)
tensor(0.)


In [177]:
# product
torch.prod(e)

tensor(0.)

In [178]:
# standard deviation
torch.std(e)

tensor(4.4272)

In [179]:
# variance
torch.var(e)

tensor(19.6000)

In [180]:
# argmax
torch.argmax(e)

tensor(5)

In [181]:
# argmin
torch.argmin(e)

tensor(1)

4. Matrix operations

In [182]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[5, 7, 3],
        [9, 4, 0]])
tensor([[5, 7],
        [5, 9],
        [9, 7]])


In [183]:
# matrix multiplication
torch.matmul(f, g)

tensor([[ 87, 119],
        [ 65,  99]])

In [184]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# Dot
torch.dot(vector1, vector2)

tensor(11)

In [185]:
# transpose
torch.transpose(f, 0, 1)

tensor([[5, 9],
        [7, 4],
        [3, 0]])

In [186]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[5., 9., 8.],
        [9., 7., 9.],
        [2., 6., 7.]])

In [187]:
# determinant
torch.det(h)

tensor(-110.)

In [188]:
# inverse
torch.inverse(h)

tensor([[ 0.0455,  0.1364, -0.2273],
        [ 0.4091, -0.1727, -0.2455],
        [-0.3636,  0.1091,  0.4182]])

5. Comparison operations

In [189]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[7, 8, 3],
        [6, 1, 5]])
tensor([[5, 0, 4],
        [3, 8, 8]])


In [190]:
# greater than
i > j

tensor([[ True,  True, False],
        [ True, False, False]])

In [191]:
# less than
i < j

tensor([[False, False,  True],
        [False,  True,  True]])

In [192]:
# equal to
i == j

tensor([[False, False, False],
        [False, False, False]])

In [193]:
# not equal to
i != j

tensor([[True, True, True],
        [True, True, True]])

6. Special functions

In [194]:
k = torch.randint(size=(2, 3), low=0, high=10, dtype=torch.float32)
k

tensor([[3., 3., 5.],
        [0., 6., 4.]])

In [195]:
# log 
torch.log(k)

tensor([[1.0986, 1.0986, 1.6094],
        [  -inf, 1.7918, 1.3863]])

In [196]:
# exp 
torch.exp(k)

tensor([[ 20.0855,  20.0855, 148.4132],
        [  1.0000, 403.4288,  54.5981]])

In [197]:
# sqrt 
torch.sqrt(k)

tensor([[1.7321, 1.7321, 2.2361],
        [0.0000, 2.4495, 2.0000]])

In [198]:
# sigmoid 
torch.sigmoid(k)

tensor([[0.9526, 0.9526, 0.9933],
        [0.5000, 0.9975, 0.9820]])

In [199]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.9526, 0.0474, 0.7311],
        [0.0474, 0.9526, 0.2689]])

In [200]:
# relu
torch.relu(k)

tensor([[3., 3., 5.],
        [0., 6., 4.]])

## Inplace Operation

In [201]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.6574, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868]])
tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])


In [202]:
m + n       # new tensor

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [203]:
m.add_(n) # same tensor

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [204]:
torch.relu(m)

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [205]:
m.relu_()

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

## Copying a Tensor

In [206]:
a = torch.rand(2,3)
a

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [207]:
b = a
b

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [208]:
a[0][0] = 0
a

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [209]:
b 

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [210]:
b = a.clone()
b

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

# Tensor Operations on GPU

In [211]:
torch.cuda.is_available()

True

In [212]:
device = torch.device('cuda')

In [213]:
# Creating a new tensor on GPU
torch.rand((2,3), device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [214]:
# moving and existing tensor to GPU
b = a.to(device)

In [215]:
import time

size = 10000

matrix_cpu1 = torch.randn(size, size)
matrix_cpu2 = torch.randn(size, size)

start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2)
cpu_time = time.time() - start_time

print(f"Time on CPU: {cpu_time:.4f} seconds")

matrix_gpu1 = matrix_cpu1.to('cuda')
matrix_gpu2 = matrix_cpu2.to('cuda')
start_time = time.time()
result_cpu = torch.matmul(matrix_gpu1, matrix_gpu2)
torch.cuda.synchronize
gpu_time = time.time() - start_time

print(f"Time on GPU: {gpu_time:.4f} seconds")

print("\nSpeedup:", cpu_time/gpu_time)

Time on CPU: 4.4850 seconds
Time on GPU: 0.0005 seconds

Speedup: 8790.396728971962


## Reshaping Tensors

In [216]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [217]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [218]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [219]:
b = torch.rand(2,3,4)
b

tensor([[[0.3932, 0.7483, 0.7985, 0.4626],
         [0.9414, 0.5752, 0.8881, 0.7989],
         [0.9514, 0.0141, 0.8903, 0.1649]],

        [[0.3162, 0.1331, 0.6763, 0.4254],
         [0.2375, 0.5430, 0.1174, 0.6532],
         [0.5115, 0.3094, 0.7907, 0.7351]]])

In [220]:
# Permute
b.permute(2, 0, 1)

tensor([[[0.3932, 0.9414, 0.9514],
         [0.3162, 0.2375, 0.5115]],

        [[0.7483, 0.5752, 0.0141],
         [0.1331, 0.5430, 0.3094]],

        [[0.7985, 0.8881, 0.8903],
         [0.6763, 0.1174, 0.7907]],

        [[0.4626, 0.7989, 0.1649],
         [0.4254, 0.6532, 0.7351]]])

In [221]:
# unsqeueze
c = torch.rand(226, 226, 3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [222]:
# squeeze
d = torch.rand(1,20)
d.squeeze(0).shape


torch.Size([20])

## NumPy and PyTorch

In [223]:
import numpy as np

In [224]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [225]:
b = a.numpy()
b

array([1, 2, 3])

In [226]:
c = np.array([1, 2,3])
c

array([1, 2, 3])

In [227]:
torch.from_numpy(c)

tensor([1, 2, 3])